// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_HalfmindScreen
void ui_HalfmindScreen_screen_init(void);
lv_obj_t * ui_HalfmindScreen;
lv_obj_t * ui_halfmindIcon;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Image4;
lv_obj_t * ui_halfmindLabel;
// CUSTOM VARIABLES
lv_obj_t * uic_HalfmindScreen;
lv_obj_t * uic_halfmindIcon;
lv_obj_t * uic_halfmindLabel;


// SCREEN: ui_OTAScreen
void ui_OTAScreen_screen_init(void);
lv_obj_t * ui_OTAScreen;
lv_obj_t * ui_textlabel;
lv_obj_t * ui_textlabel1;
lv_obj_t * ui_textlabel2;
// CUSTOM VARIABLES
lv_obj_t * uic_textlabel;
lv_obj_t * uic_textlabel1;
lv_obj_t * uic_textlabel2;


// SCREEN: ui_ActivateScreen
void ui_ActivateScreen_screen_init(void);
lv_obj_t * ui_ActivateScreen;
lv_obj_t * ui_textlabel4;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Image5;
// CUSTOM VARIABLES
lv_obj_t * uic_ActivateScreen;
lv_obj_t * uic_textlabel4;


// SCREEN: ui_TaskScreen
void ui_TaskScreen_screen_init(void);
lv_obj_t * ui_TaskScreen;
lv_obj_t * ui_textlabel5;
lv_obj_t * ui_textlabel6;
lv_obj_t * ui_Container3;
lv_obj_t * ui_startLabel;
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Button2;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label8;
lv_obj_t * ui_endLabel;
// CUSTOM VARIABLES
lv_obj_t * uic_TaskScreen;
lv_obj_t * uic_textlabel5;
lv_obj_t * uic_textlabel6;
lv_obj_t * uic_startLabel;
lv_obj_t * uic_endLabel;


// SCREEN: ui_FocusScreen
void ui_FocusScreen_screen_init(void);
lv_obj_t * ui_FocusScreen;
lv_obj_t * ui_Arc1;
lv_obj_t * ui_textlabel7;
lv_obj_t * ui_textlabel3;
// CUSTOM VARIABLES
lv_obj_t * uic_FocusScreen;
lv_obj_t * uic_textlabel7;
lv_obj_t * uic_textlabel3;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_1598583580[1] = {&ui_img_1859145046};

///////////////////// TEST LVGL SETTINGS ////////////////////
// #if LV_COLOR_DEPTH != 16
//     #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
// #endif
// #if LV_COLOR_16_SWAP !=0
//     #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
// #endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_HalfmindScreen_screen_init();
    ui_OTAScreen_screen_init();
    ui_ActivateScreen_screen_init();
    ui_TaskScreen_screen_init();
    ui_FocusScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_HalfmindScreen);
}
