// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_HalfmindScreen
void ui_HalfmindScreen_screen_init(void);
lv_obj_t * ui_HalfmindScreen;
lv_obj_t * ui_Image15;
// CUSTOM VARIABLES
lv_obj_t * uic_HalfmindScreen;


// SCREEN: ui_ActiveScreen
void ui_ActiveScreen_screen_init(void);
lv_obj_t * ui_ActiveScreen;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Activate1;
lv_obj_t * ui_Activate2;
// CUSTOM VARIABLES
lv_obj_t * uic_ActiveScreen;


// SCREEN: ui_OTAScreen
void ui_OTAScreen_screen_init(void);
lv_obj_t * ui_OTAScreen;
lv_obj_t * ui_Container2;
lv_obj_t * ui_VersionChange;
lv_obj_t * ui_OTAWaitingGuide;
lv_obj_t * ui_scrollbar3;
lv_obj_t * ui_Arc4;
lv_obj_t * ui_VersionDescribtion;
lv_obj_t * ui_OTAButton;
lv_obj_t * ui_OTAButtonCancel;
lv_obj_t * ui_OTAButtonStart;
lv_obj_t * ui_RetryCheckVersionButton;
lv_obj_t * ui_RetryCheckVersionButtonCancel;
lv_obj_t * ui_RetryCheckVersionButtonRetry;
lv_obj_t * ui_UpToDate;
lv_obj_t * ui_UpToDate1;
lv_obj_t * ui_FailGetMsg;
lv_obj_t * ui_FailGetMsg1;
lv_obj_t * ui_CheckingUpd;
lv_obj_t * ui_UpToDate2;
lv_obj_t * ui_UpdAvailable;
lv_obj_t * ui_UpdAvailable1;
// CUSTOM VARIABLES
lv_obj_t * uic_VersionChange;
lv_obj_t * uic_OTAWaitingGuide;
lv_obj_t * uic_VersionChange;
lv_obj_t * uic_OTAButtonStart;
lv_obj_t * uic_RetryCheckVersionButton;
lv_obj_t * uic_HostActiveCancel;
lv_obj_t * uic_RetryCheckVersionButtonRetry;
lv_obj_t * uic_NewFirmware;
lv_obj_t * uic_UpToDate2;
lv_obj_t * uic_NewFirmware;
lv_obj_t * uic_UpToDate2;
lv_obj_t * uic_NewFirmware;
lv_obj_t * uic_UpToDate2;
lv_obj_t * uic_NewFirmware;
lv_obj_t * uic_UpToDate2;


// SCREEN: ui_TaskScreen
void ui_TaskScreen_screen_init(void);
lv_obj_t * ui_TaskScreen;
lv_obj_t * ui_HaveTaskContainer;
lv_obj_t * ui_TaskContainer;
lv_obj_t * ui_Button1;
lv_obj_t * ui_chooseTaskF;
lv_obj_t * ui_chooseTask1;
lv_obj_t * ui_Button2;
lv_obj_t * ui_chooseTaskS;
lv_obj_t * ui_chooseTask2;
lv_obj_t * ui_Button3;
lv_obj_t * ui_chooseTaskT;
lv_obj_t * ui_chooseTask11;
lv_obj_t * ui_scrollbar;
lv_obj_t * ui_Arc1;
lv_obj_t * ui_NoTaskContainer;
lv_obj_t * ui_Notask;
lv_obj_t * ui_NotaskTip1;
lv_obj_t * ui_NotaskTip2;
lv_obj_t * ui_NotaskTip3;
// CUSTOM VARIABLES
lv_obj_t * uic_TaskScreen;
lv_obj_t * uic_chooseTaskF;
lv_obj_t * uic_chooseTaskS;
lv_obj_t * uic_chooseTaskT;


// SCREEN: ui_OperatingScreen
void ui_OperatingScreen_screen_init(void);
lv_obj_t * ui_OperatingScreen;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_NoOperate;
lv_obj_t * ui_NoOperatetTime;
lv_obj_t * ui_Label8;
lv_obj_t * ui_NoOperateChooseButton;
lv_obj_t * ui_NoOperateChooseCancel;
lv_obj_t * ui_NoOperateChooseStart;
lv_obj_t * ui_NoOperateAutoGuide;
lv_obj_t * ui_NoOperateAutoGuidePading;
lv_obj_t * ui_RecordOperate;
lv_obj_t * ui_RecordOperateUpText;
lv_obj_t * ui_Label9;
lv_obj_t * ui_RecordOperateTime;
lv_obj_t * ui_Label7;
lv_obj_t * ui_RecordAgain;
lv_obj_t * ui_RecordOperateMiddleText;
lv_obj_t * ui_RecordOperateButton;
lv_obj_t * ui_Image8;
lv_obj_t * ui_RecordComfirmButton;
lv_obj_t * ui_RecordComfirmCancel;
lv_obj_t * ui_RecordComfirmFinish;
lv_obj_t * ui_RecordOperateDownText;
lv_obj_t * ui_RecordOperateMiddleTextPadding;
lv_obj_t * ui_RecordOperateDownTextPadding;
lv_obj_t * ui_TaskOperate;
lv_obj_t * ui_TaskName;
lv_obj_t * ui_Label3;
lv_obj_t * ui_TaskOperatetTime;
lv_obj_t * ui_Label5;
lv_obj_t * ui_TaskOperateAutoGuide;
lv_obj_t * ui_TaskOperateButton;
lv_obj_t * ui_TaskOperateCancel;
lv_obj_t * ui_TaskOperateStart;
lv_obj_t * ui_TaskOperateAutoGuidePading;
// CUSTOM VARIABLES
lv_obj_t * uic_OperatingScreen;
lv_obj_t * uic_RecordOperateTime;
lv_obj_t * uic_RecordOperateTime;
lv_obj_t * uic_RecordComfirmFinish;
lv_obj_t * uic_RecordOperateDownText;
lv_obj_t * uic_RecordOperateDownText;


// SCREEN: ui_UpdateScreen
void ui_UpdateScreen_screen_init(void);
lv_obj_t * ui_UpdateScreen;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_VersionnNmber;
lv_obj_t * ui_OTAUpdating;
lv_obj_t * ui_OTAUpdating1;
lv_obj_t * ui_OTASuccess;
lv_obj_t * ui_OTASuccess1;
lv_obj_t * ui_OTAFail;
lv_obj_t * ui_OTAFail1;
lv_obj_t * ui_Bar;
// CUSTOM VARIABLES
lv_obj_t * uic_VersionnNmber;
lv_obj_t * uic_Updating;
lv_obj_t * uic_Updating2;
lv_obj_t * uic_Updating;
lv_obj_t * uic_Updating2;
lv_obj_t * uic_Updating;
lv_obj_t * uic_Updating2;


// SCREEN: ui_ShutdownScreen
void ui_ShutdownScreen_screen_init(void);
lv_obj_t * ui_ShutdownScreen;
lv_obj_t * ui_Panel13;
lv_obj_t * ui_ShutdownGuide;
lv_obj_t * ui_ShutdownGuide2;
lv_obj_t * ui_Battery;
// CUSTOM VARIABLES
lv_obj_t * uic_ShutdownScreen;
lv_obj_t * uic_ShutdownGuide;
lv_obj_t * uic_ShutdownGuide;


// SCREEN: ui_HostActiveScreen
void ui_HostActiveScreen_screen_init(void);
lv_obj_t * ui_HostActiveScreen;
lv_obj_t * ui_ConnectingWIFI;
lv_obj_t * ui_HostActiveGuide;
lv_obj_t * ui_WIFIname;
lv_obj_t * ui_Label2;
lv_obj_t * ui_HostActiveAutoTime;
lv_obj_t * ui_HostActiveAutoTimePanding;
lv_obj_t * ui_HostActivateSuccess;
lv_obj_t * ui_SlaveActiveGuide;
lv_obj_t * ui_DisconnectWIFI;
lv_obj_t * ui_HostActiveCancel;
lv_obj_t * ui_Disconnectwifiname;
lv_obj_t * ui_Label4;
lv_obj_t * ui_HostActiveRetry;
// CUSTOM VARIABLES
lv_obj_t * uic_HostActiveScreen;
lv_obj_t * uic_HostActiveAutoTime;
lv_obj_t * uic_HostActiveAutoTime;
lv_obj_t * uic_HostActiveAutoTime;
lv_obj_t * uic_HostActiveCancel;
lv_obj_t * uic_HostActiveRetry;


// SCREEN: ui_SlaveActiveScreen
void ui_SlaveActiveScreen_screen_init(void);
lv_obj_t * ui_SlaveActiveScreen;
lv_obj_t * ui_ConnectingHost;
lv_obj_t * ui_Username;
lv_obj_t * ui_Label6;
lv_obj_t * ui_SlaveActiveCancel;
lv_obj_t * ui_SlaveActiveConfirm;
lv_obj_t * ui_TestConnecting;
lv_obj_t * ui_ConnectGuide1;
lv_obj_t * ui_Label10;
lv_obj_t * ui_SlaveActivateAccept;
lv_obj_t * ui_SlaveActivateRetry;
lv_obj_t * ui_SlaveActivateBad;
lv_obj_t * ui_SlaveActivateGood;
lv_obj_t * ui_SlaveActivateTooClose;
lv_obj_t * ui_SlaveActivateLoseConnection;
// CUSTOM VARIABLES
lv_obj_t * uic_SlaveActiveScreen;
lv_obj_t * uic_HostActiveCancel;
lv_obj_t * uic_HostActiveRetry;
lv_obj_t * uic_SlaveActivateLoseConnection;


// SCREEN: ui_SleepFocusScreen
void ui_SleepFocusScreen_screen_init(void);
lv_obj_t * ui_SleepFocusScreen;
lv_obj_t * ui_TaskFocus5;
lv_obj_t * ui_CoutdownBar;
lv_obj_t * ui_SleepTaskFocusTime;
lv_obj_t * ui_FocusTime5;
lv_obj_t * ui_SleepTaskFocusName;
lv_obj_t * ui_Task5;
lv_obj_t * ui_SleepTimeFocusTime;
lv_obj_t * ui_FocusTime4;
lv_obj_t * ui_SleepRecordFocusName;
// CUSTOM VARIABLES
lv_obj_t * uic_SleepFocusScreen;
lv_obj_t * uic_CoutdownBar;
lv_obj_t * uic_FocusTime1;
lv_obj_t * uic_FocusTime1;
lv_obj_t * uic_FocusTask;
lv_obj_t * uic_Task;
lv_obj_t * uic_SleepTimeFocusTime;
lv_obj_t * uic_FocusTime1;
lv_obj_t * uic_SleepRecordFocusName;


// SCREEN: ui_FocusScreen
void ui_FocusScreen_screen_init(void);
lv_obj_t * ui_FocusScreen;
lv_obj_t * ui_TaskFocus;
lv_obj_t * ui_TaskFocus1;
lv_obj_t * ui_FocusTask;
lv_obj_t * ui_Task;
lv_obj_t * ui_TaskFocus2;
lv_obj_t * ui_TaskFocusTime;
lv_obj_t * ui_FocusTime2;
lv_obj_t * ui_TaskFocusWarning;
lv_obj_t * ui_Image4;
lv_obj_t * ui_Image5;
lv_obj_t * ui_RecordFocus;
lv_obj_t * ui_RecordFocus1;
lv_obj_t * ui_Image7;
lv_obj_t * ui_RecordFocus2;
lv_obj_t * ui_RecordFocusTime;
lv_obj_t * ui_FocusTime1;
lv_obj_t * ui_RecordFocusWarning;
lv_obj_t * ui_Image6;
lv_obj_t * ui_Image2;
lv_obj_t * ui_NoFocus;
lv_obj_t * ui_NoFocusTime;
lv_obj_t * ui_NoFocusTime2;
lv_obj_t * ui_NoFocusWarning;
lv_obj_t * ui_Image9;
lv_obj_t * ui_Image3;
lv_obj_t * ui_Image10;
lv_obj_t * ui_Image11;
lv_obj_t * ui_Image12;
lv_obj_t * ui_Image13;
// CUSTOM VARIABLES
lv_obj_t * uic_FocusScreen;
lv_obj_t * uic_FocusTask;
lv_obj_t * uic_Task;
lv_obj_t * uic_FocusTime1;
lv_obj_t * uic_FocusTime1;
lv_obj_t * uic_FocusTime1;
lv_obj_t * uic_FocusTime1;
lv_obj_t * uic_NoFocusWarning;


// SCREEN: ui_MessageScreen
void ui_MessageScreen_screen_init(void);
lv_obj_t * ui_MessageScreen;
lv_obj_t * ui_scrollbar2;
lv_obj_t * ui_Arc3;
lv_obj_t * ui_Device;
lv_obj_t * ui_Message1;
lv_obj_t * ui_Message2;
lv_obj_t * ui_Message3;
lv_obj_t * ui_Message4;
lv_obj_t * ui_Message5;
lv_obj_t * ui_Devideinfo;
lv_obj_t * ui_ConnectionHost;
lv_obj_t * ui_Message11;
lv_obj_t * ui_Message12;
lv_obj_t * ui_Message13;
lv_obj_t * ui_Message14;
lv_obj_t * ui_Message15;
lv_obj_t * ui_ConnectionInfoHost;
lv_obj_t * ui_ConnectionSlave;
lv_obj_t * ui_Message111;
lv_obj_t * ui_Message121;
lv_obj_t * ui_Message131;
lv_obj_t * ui_Message141;
lv_obj_t * ui_Message151;
lv_obj_t * ui_ConnectionInfoSlave;
lv_obj_t * ui_Power;
lv_obj_t * ui_Message21;
lv_obj_t * ui_Message22;
lv_obj_t * ui_Reboot;
lv_obj_t * ui_OTA;
lv_obj_t * ui_PowerInfo;
// CUSTOM VARIABLES
lv_obj_t * uic_HalfmindScreen;
lv_obj_t * uic_MessageFirmware;
lv_obj_t * uic_MessageLanguage;
lv_obj_t * uic_MessageFirmware;
lv_obj_t * uic_MessageLanguage;
lv_obj_t * uic_MessageFirmware;
lv_obj_t * uic_MessageLanguage;
lv_obj_t * uic_HostActiveCancel;
lv_obj_t * uic_HostActiveCancel;


// SCREEN: ui_SleepClockScreen
void ui_SleepClockScreen_screen_init(void);
lv_obj_t * ui_SleepClockScreen;
lv_obj_t * ui_TaskFocus4;
lv_obj_t * ui_TodoNum;
lv_obj_t * ui_Task2;
lv_obj_t * ui_Date;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Hour;
lv_obj_t * ui_Label13;
lv_obj_t * ui_MinuteBar;
// CUSTOM VARIABLES
lv_obj_t * uic_FocusScreen;
lv_obj_t * uic_TodoNum;
lv_obj_t * uic_Task;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_activate[3] = {&ui_img_activate1_png, &ui_img_activate2_png, &ui_img_activate3_png};
const lv_img_dsc_t * ui_imgset_tips[3] = {&ui_img_tips1_png, &ui_img_tips2_png, &ui_img_tips3_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
// #if LV_COLOR_DEPTH != 8
//     #error "LV_COLOR_DEPTH should be 8bit to match SquareLine Studio's settings"
// #endif
// #if LV_COLOR_16_SWAP !=0
//     #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
// #endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_mono_init(dispp,false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_HalfmindScreen_screen_init();
    ui_ActiveScreen_screen_init();
    ui_OTAScreen_screen_init();
    ui_TaskScreen_screen_init();
    ui_OperatingScreen_screen_init();
    ui_UpdateScreen_screen_init();
    ui_ShutdownScreen_screen_init();
    ui_HostActiveScreen_screen_init();
    ui_SlaveActiveScreen_screen_init();
    ui_SleepFocusScreen_screen_init();
    ui_FocusScreen_screen_init();
    ui_MessageScreen_screen_init();
    ui_SleepClockScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_HalfmindScreen);
}
