// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_HalfmindScreen
void ui_HalfmindScreen_screen_init(void);
extern lv_obj_t * ui_HalfmindScreen;
// CUSTOM VARIABLES
extern lv_obj_t * uic_HalfmindScreen;

// SCREEN: ui_ActiveScreen
void ui_ActiveScreen_screen_init(void);
extern lv_obj_t * ui_ActiveScreen;
extern lv_obj_t * ui_ActiveGuide;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ActiveScreen;
extern lv_obj_t * uic_HostGuide;

// SCREEN: ui_OTAScreen
void ui_OTAScreen_screen_init(void);
extern lv_obj_t * ui_OTAScreen;
extern lv_obj_t * ui_NewFirmware;
extern lv_obj_t * ui_NewFirmware2;
extern lv_obj_t * ui_OperateGuide;
extern lv_obj_t * ui_OperateGuide2;
extern lv_obj_t * ui_VersionChange;
// CUSTOM VARIABLES
extern lv_obj_t * uic_NewFirmware;
extern lv_obj_t * uic_NewFirmware2;
extern lv_obj_t * uic_OperateGuide;
extern lv_obj_t * uic_OperateGuide2;
extern lv_obj_t * uic_VersionChange;

// SCREEN: ui_TaskScreen
void ui_TaskScreen_screen_init(void);
extern lv_obj_t * ui_TaskScreen;
extern lv_obj_t * ui_HaveTaskContainer;
extern lv_obj_t * ui_startlabel;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_chooseTaskF;
extern lv_obj_t * ui_chooseTask1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_chooseTaskS;
extern lv_obj_t * ui_chooseTask2;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_chooseTaskT;
extern lv_obj_t * ui_chooseTask11;
extern lv_obj_t * ui_endlabel;
extern lv_obj_t * ui_NoTaskContainer;
extern lv_obj_t * ui_NoTaskNote;
extern lv_obj_t * ui_NoTaskNote14;
extern lv_obj_t * ui_NoTaskNote2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_TaskScreen;
extern lv_obj_t * uic_HaveTaskContainer;
extern lv_obj_t * uic_chooseTaskF;
extern lv_obj_t * uic_chooseTaskS;
extern lv_obj_t * uic_chooseTaskT;
extern lv_obj_t * uic_NoTaskContainer;
extern lv_obj_t * uic_NoTaskNote1;
extern lv_obj_t * uic_NoTaskNote5;
extern lv_obj_t * uic_NoTaskNote6;

// SCREEN: ui_OperatingScreen
void ui_OperatingScreen_screen_init(void);
extern lv_obj_t * ui_OperatingScreen;
extern lv_obj_t * ui_OperatingTime;
extern lv_obj_t * ui_Time2;
extern lv_obj_t * ui_Time3;
// CUSTOM VARIABLES
extern lv_obj_t * uic_OperatingScreen;
extern lv_obj_t * uic_OperatingTime;

// SCREEN: ui_FocusScreen
void ui_FocusScreen_screen_init(void);
extern lv_obj_t * ui_FocusScreen;
extern lv_obj_t * ui_FocusTask;
extern lv_obj_t * ui_Task;
extern lv_obj_t * ui_FocusTime;
// CUSTOM VARIABLES
extern lv_obj_t * uic_FocusScreen;
extern lv_obj_t * uic_FocusTask;
extern lv_obj_t * uic_Task2;
extern lv_obj_t * uic_FocusTime1;

// SCREEN: ui_UpdateScreen
void ui_UpdateScreen_screen_init(void);
extern lv_obj_t * ui_UpdateScreen;
extern lv_obj_t * ui_Updating;
extern lv_obj_t * ui_Updating2;
extern lv_obj_t * ui_VersionnNmber;
extern lv_obj_t * ui_Bar;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Updating;
extern lv_obj_t * uic_Updating2;
extern lv_obj_t * uic_VersionnNmber;

// SCREEN: ui_ShutdownScreen
void ui_ShutdownScreen_screen_init(void);
extern lv_obj_t * ui_ShutdownScreen;
extern lv_obj_t * ui_ShutdownGuide;
extern lv_obj_t * ui_ShutdownGuide2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ShutdownScreen;
extern lv_obj_t * uic_ShutdownGuide;
extern lv_obj_t * uic_ShutdownGuide;

// SCREEN: ui_HostActiveScreen
void ui_HostActiveScreen_screen_init(void);
extern lv_obj_t * ui_HostActiveScreen;
extern lv_obj_t * ui_HostName;
extern lv_obj_t * ui_HostInf;
// CUSTOM VARIABLES
extern lv_obj_t * uic_HostActiveScreen;
extern lv_obj_t * uic_HostName;
extern lv_obj_t * uic_HostInf;

// SCREEN: ui_SlaveActiveScreen
void ui_SlaveActiveScreen_screen_init(void);
extern lv_obj_t * ui_SlaveActiveScreen;
extern lv_obj_t * ui_SlaveName;
extern lv_obj_t * ui_SlaveInf;
// CUSTOM VARIABLES
extern lv_obj_t * uic_SlaveActiveScreen;
extern lv_obj_t * uic_SlaveInf;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_Chinese_20);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
