// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ActiveScreen_screen_init(void)
{
    ui_ActiveScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ActiveScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ActiveGuide = lv_label_create(ui_ActiveScreen);
    lv_obj_set_width(ui_ActiveGuide, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ActiveGuide, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ActiveGuide, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ActiveGuide, "Use APP to active Host\nor\nUse Host to active Slave");
    lv_obj_set_style_text_color(ui_ActiveGuide, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ActiveGuide, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ActiveGuide, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ActiveGuide, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_ActiveGuide);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -1);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Use APP to active Host\nor\nUse Host to active Slave");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_ActiveGuide);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Use APP to active Host\nor\nUse Host to active Slave");
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_ActiveScreen = ui_ActiveScreen;
    uic_HostGuide = ui_ActiveGuide;

}
