// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ActiveScreen_screen_init(void)
{
    ui_ActiveScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ActiveScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_ActiveScreen);
    lv_obj_set_width(ui_Panel2, 250);
    lv_obj_set_height(ui_Panel2, 122);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Activate1 = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_Activate1, &ui_img_activate1_png);
    lv_obj_set_width(ui_Activate1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Activate1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Activate1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Activate1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Activate1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Activate2 = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_Activate2, &ui_img_activate2_png);
    lv_obj_set_width(ui_Activate2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Activate2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Activate2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Activate2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Activate2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Activate3 = lv_img_create(ui_Panel2);
    lv_img_set_src(ui_Activate3, &ui_img_activate3_png);
    lv_obj_set_width(ui_Activate3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Activate3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Activate3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Activate3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Activate3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_ActiveScreen = ui_ActiveScreen;

}
