// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ActivateScreen_screen_init(void)
{
    ui_ActivateScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ActivateScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_textlabel4 = lv_label_create(ui_ActivateScreen);
    lv_obj_set_width(ui_textlabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textlabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textlabel4, 62);
    lv_obj_set_y(ui_textlabel4, 10);
    lv_obj_set_align(ui_textlabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textlabel4, "Scan with App\n   to Activate");
    lv_obj_set_style_text_color(ui_textlabel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_textlabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_textlabel4, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_ActivateScreen);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 100);
    lv_obj_set_height(ui_Container2, 100);
    lv_obj_set_x(ui_Container2, -52);
    lv_obj_set_y(ui_Container2, 0);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_Container2);
    lv_img_set_src(ui_Image5, &ui_img_erweima_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 502
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 528
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image5, 64);

    uic_ActivateScreen = ui_ActivateScreen;
    uic_textlabel4 = ui_textlabel4;

}
