// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_BindScreen_screen_init(void)
{
    ui_BindScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BindScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BindGuide = lv_label_create(ui_BindScreen);
    lv_obj_set_width(ui_BindGuide, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BindGuide, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BindGuide, 0);
    lv_obj_set_y(ui_BindGuide, -38);
    lv_obj_set_align(ui_BindGuide, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BindGuide, "Move close to activate");
    lv_obj_set_style_text_color(ui_BindGuide, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BindGuide, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_BindGuide, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BindGuide, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_BindGuide);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -1);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Move close to activate");
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_BindGuide);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 1);
    lv_obj_set_y(ui_Label3, 0);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Move close to activate");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Username = lv_label_create(ui_BindScreen);
    lv_obj_set_width(ui_Username, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Username, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Username, 0);
    lv_obj_set_y(ui_Username, 2);
    lv_obj_set_align(ui_Username, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Username, "Username: jeg");

    ui_Wifiname = lv_label_create(ui_BindScreen);
    lv_obj_set_width(ui_Wifiname, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifiname, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifiname, 0);
    lv_obj_set_y(ui_Wifiname, 20);
    lv_obj_set_align(ui_Wifiname, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Wifiname, "WIFI name:1");

    ui_WIFIPassword = lv_label_create(ui_BindScreen);
    lv_obj_set_width(ui_WIFIPassword, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WIFIPassword, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WIFIPassword, -1);
    lv_obj_set_y(ui_WIFIPassword, 38);
    lv_obj_set_align(ui_WIFIPassword, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WIFIPassword, "WIFI Password: 11111111");

    ui_Firmwareversion = lv_label_create(ui_BindScreen);
    lv_obj_set_width(ui_Firmwareversion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Firmwareversion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Firmwareversion, 0);
    lv_obj_set_y(ui_Firmwareversion, -16);
    lv_obj_set_align(ui_Firmwareversion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Firmwareversion, "Version:2.0.1");

    uic_BindScreen = ui_BindScreen;
    uic_BindGuide = ui_BindGuide;
    uic_Username = ui_Username;
    uic_Wifiname = ui_Wifiname;
    uic_WIFIPassword = ui_WIFIPassword;
    uic_Firmwareversion = ui_Firmwareversion;

}
