// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_FactoryScreen_screen_init(void)
{
    ui_FactoryScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_FactoryScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonPanel = lv_obj_create(ui_FactoryScreen);
    lv_obj_remove_style_all(ui_ButtonPanel);
    lv_obj_set_width(ui_ButtonPanel, 250);
    lv_obj_set_height(ui_ButtonPanel, 122);
    lv_obj_set_align(ui_ButtonPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ButtonPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ButtonPanel, &ui_img_buttonpanel_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ButtonPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ButtonPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMask1 = lv_obj_create(ui_ButtonPanel);
    lv_obj_set_width(ui_ButtonMask1, 63);
    lv_obj_set_height(ui_ButtonMask1, 64);
    lv_obj_add_flag(ui_ButtonMask1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ButtonMask1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonMask1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMask1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMask1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonMask1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonMask1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ButtonMask1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ButtonMask1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMask2 = lv_obj_create(ui_ButtonPanel);
    lv_obj_set_width(ui_ButtonMask2, 63);
    lv_obj_set_height(ui_ButtonMask2, 64);
    lv_obj_set_x(ui_ButtonMask2, 63);
    lv_obj_set_y(ui_ButtonMask2, 0);
    lv_obj_add_flag(ui_ButtonMask2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ButtonMask2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonMask2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMask2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMask2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonMask2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonMask2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ButtonMask2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ButtonMask2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMask3 = lv_obj_create(ui_ButtonPanel);
    lv_obj_set_width(ui_ButtonMask3, 63);
    lv_obj_set_height(ui_ButtonMask3, 64);
    lv_obj_set_x(ui_ButtonMask3, 126);
    lv_obj_set_y(ui_ButtonMask3, 0);
    lv_obj_add_flag(ui_ButtonMask3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ButtonMask3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonMask3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMask3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMask3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonMask3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonMask3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ButtonMask3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ButtonMask3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMask4 = lv_obj_create(ui_ButtonPanel);
    lv_obj_set_width(ui_ButtonMask4, 63);
    lv_obj_set_height(ui_ButtonMask4, 64);
    lv_obj_set_x(ui_ButtonMask4, 188);
    lv_obj_set_y(ui_ButtonMask4, 0);
    lv_obj_add_flag(ui_ButtonMask4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ButtonMask4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonMask4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMask4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMask4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonMask4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonMask4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ButtonMask4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ButtonMask4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMask5 = lv_obj_create(ui_ButtonPanel);
    lv_obj_set_width(ui_ButtonMask5, 63);
    lv_obj_set_height(ui_ButtonMask5, 64);
    lv_obj_set_x(ui_ButtonMask5, 0);
    lv_obj_set_y(ui_ButtonMask5, 60);
    lv_obj_add_flag(ui_ButtonMask5, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ButtonMask5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonMask5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMask5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMask5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonMask5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonMask5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ButtonMask5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ButtonMask5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMask6 = lv_obj_create(ui_ButtonPanel);
    lv_obj_set_width(ui_ButtonMask6, 63);
    lv_obj_set_height(ui_ButtonMask6, 64);
    lv_obj_set_x(ui_ButtonMask6, 63);
    lv_obj_set_y(ui_ButtonMask6, 60);
    lv_obj_add_flag(ui_ButtonMask6, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ButtonMask6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonMask6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMask6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMask6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonMask6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonMask6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ButtonMask6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ButtonMask6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMask7 = lv_obj_create(ui_ButtonPanel);
    lv_obj_set_width(ui_ButtonMask7, 63);
    lv_obj_set_height(ui_ButtonMask7, 64);
    lv_obj_set_x(ui_ButtonMask7, 126);
    lv_obj_set_y(ui_ButtonMask7, 60);
    lv_obj_add_flag(ui_ButtonMask7, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ButtonMask7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonMask7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMask7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMask7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonMask7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonMask7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ButtonMask7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ButtonMask7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonMask8 = lv_obj_create(ui_ButtonPanel);
    lv_obj_set_width(ui_ButtonMask8, 63);
    lv_obj_set_height(ui_ButtonMask8, 63);
    lv_obj_set_x(ui_ButtonMask8, 188);
    lv_obj_set_y(ui_ButtonMask8, 60);
    lv_obj_add_flag(ui_ButtonMask8, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_ButtonMask8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonMask8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonMask8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonMask8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ButtonMask8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonMask8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ButtonMask8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ButtonMask8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeakerPanel = lv_obj_create(ui_FactoryScreen);
    lv_obj_remove_style_all(ui_SpeakerPanel);
    lv_obj_set_width(ui_SpeakerPanel, 250);
    lv_obj_set_height(ui_SpeakerPanel, 122);
    lv_obj_set_align(ui_SpeakerPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SpeakerPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CharacterName = lv_label_create(ui_SpeakerPanel);
    lv_obj_set_width(ui_CharacterName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CharacterName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CharacterName, 0);
    lv_obj_set_y(ui_CharacterName, -35);
    lv_obj_set_align(ui_CharacterName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CharacterName, "Speaker");
    lv_obj_set_style_text_font(ui_CharacterName, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_CharacterName);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -1);
    lv_obj_set_y(ui_Label12, 0);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Speaker");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CharacterDescribe = lv_label_create(ui_SpeakerPanel);
    lv_obj_set_width(ui_CharacterDescribe, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CharacterDescribe, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CharacterDescribe, 0);
    lv_obj_set_y(ui_CharacterDescribe, 10);
    lv_obj_set_align(ui_CharacterDescribe, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CharacterDescribe, "Volume : 100%");
    lv_obj_set_style_text_align(ui_CharacterDescribe, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CharacterDescribe, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordRetryDescribtion = lv_img_create(ui_SpeakerPanel);
    lv_img_set_src(ui_RecordRetryDescribtion, &ui_img_recordagain_png);
    lv_obj_set_width(ui_RecordRetryDescribtion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RecordRetryDescribtion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RecordRetryDescribtion, 0);
    lv_obj_set_y(ui_RecordRetryDescribtion, 10);
    lv_obj_set_align(ui_RecordRetryDescribtion, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RecordRetryDescribtion, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RecordRetryDescribtion, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PowerPanel = lv_obj_create(ui_FactoryScreen);
    lv_obj_remove_style_all(ui_PowerPanel);
    lv_obj_set_width(ui_PowerPanel, 250);
    lv_obj_set_height(ui_PowerPanel, 122);
    lv_obj_set_align(ui_PowerPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PowerPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PowerPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PowerName = lv_label_create(ui_PowerPanel);
    lv_obj_set_width(ui_PowerName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PowerName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PowerName, 0);
    lv_obj_set_y(ui_PowerName, -35);
    lv_obj_set_align(ui_PowerName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PowerName, "Power");
    lv_obj_set_style_text_font(ui_PowerName, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_PowerName);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -1);
    lv_obj_set_y(ui_Label11, 0);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Power");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryDescribtion = lv_label_create(ui_PowerPanel);
    lv_obj_set_width(ui_BatteryDescribtion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryDescribtion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryDescribtion, 0);
    lv_obj_set_y(ui_BatteryDescribtion, 10);
    lv_obj_set_align(ui_BatteryDescribtion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryDescribtion, "Battery:Not detected\n");
    lv_obj_set_style_text_align(ui_BatteryDescribtion, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BatteryDescribtion, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WireDescribtion = lv_label_create(ui_PowerPanel);
    lv_obj_set_width(ui_WireDescribtion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WireDescribtion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WireDescribtion, 0);
    lv_obj_set_y(ui_WireDescribtion, 30);
    lv_obj_set_align(ui_WireDescribtion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WireDescribtion, "Wire:Detected");
    lv_obj_set_style_text_align(ui_WireDescribtion, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WireDescribtion, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_CharacterName = ui_CharacterName;
    uic_CharacterName = ui_CharacterDescribe;
    uic_CharacterName = ui_PowerName;
    uic_CharacterName = ui_BatteryDescribtion;
    uic_CharacterName = ui_WireDescribtion;

}
