// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_FactoryScreen_screen_init(void)
{
    ui_FactoryScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_FactoryScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonPanel = lv_obj_create(ui_FactoryScreen);
    lv_obj_remove_style_all(ui_ButtonPanel);
    lv_obj_set_width(ui_ButtonPanel, 250);
    lv_obj_set_height(ui_ButtonPanel, 122);
    lv_obj_set_align(ui_ButtonPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ButtonPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_ButtonPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ButtonPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_ButtonPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_ButtonPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonCheck = lv_label_create(ui_ButtonPanel);
    lv_obj_set_width(ui_ButtonCheck, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ButtonCheck, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ButtonCheck, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ButtonCheck, "1  2  3  4\n5  6  7  8");
    lv_obj_set_style_text_letter_space(ui_ButtonCheck, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_ButtonCheck, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ButtonCheck, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ButtonCheck, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpeakerPanel = lv_obj_create(ui_FactoryScreen);
    lv_obj_remove_style_all(ui_SpeakerPanel);
    lv_obj_set_width(ui_SpeakerPanel, 250);
    lv_obj_set_height(ui_SpeakerPanel, 122);
    lv_obj_set_align(ui_SpeakerPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SpeakerPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_SpeakerPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CharacterName = lv_label_create(ui_SpeakerPanel);
    lv_obj_set_width(ui_CharacterName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CharacterName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CharacterName, 0);
    lv_obj_set_y(ui_CharacterName, -35);
    lv_obj_set_align(ui_CharacterName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CharacterName, "Speaker");
    lv_obj_set_style_text_font(ui_CharacterName, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_CharacterName);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, -1);
    lv_obj_set_y(ui_Label12, 0);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "Speaker");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CharacterDescribe = lv_label_create(ui_SpeakerPanel);
    lv_obj_set_width(ui_CharacterDescribe, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CharacterDescribe, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CharacterDescribe, 0);
    lv_obj_set_y(ui_CharacterDescribe, 10);
    lv_obj_set_align(ui_CharacterDescribe, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CharacterDescribe, "Volume : 100%");
    lv_obj_set_style_text_align(ui_CharacterDescribe, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CharacterDescribe, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RecordRetryDescribtion = lv_img_create(ui_SpeakerPanel);
    lv_img_set_src(ui_RecordRetryDescribtion, &ui_img_recordagain_png);
    lv_obj_set_width(ui_RecordRetryDescribtion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RecordRetryDescribtion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RecordRetryDescribtion, 0);
    lv_obj_set_y(ui_RecordRetryDescribtion, 10);
    lv_obj_set_align(ui_RecordRetryDescribtion, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RecordRetryDescribtion, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RecordRetryDescribtion, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PowerPanel = lv_obj_create(ui_FactoryScreen);
    lv_obj_remove_style_all(ui_PowerPanel);
    lv_obj_set_width(ui_PowerPanel, 250);
    lv_obj_set_height(ui_PowerPanel, 122);
    lv_obj_set_align(ui_PowerPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PowerPanel, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PowerPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PowerName = lv_label_create(ui_PowerPanel);
    lv_obj_set_width(ui_PowerName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PowerName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PowerName, 0);
    lv_obj_set_y(ui_PowerName, -35);
    lv_obj_set_align(ui_PowerName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PowerName, "Power");
    lv_obj_set_style_text_font(ui_PowerName, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_PowerName);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -1);
    lv_obj_set_y(ui_Label11, 0);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Power");
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BatteryDescribtion = lv_label_create(ui_PowerPanel);
    lv_obj_set_width(ui_BatteryDescribtion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryDescribtion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryDescribtion, 0);
    lv_obj_set_y(ui_BatteryDescribtion, 10);
    lv_obj_set_align(ui_BatteryDescribtion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryDescribtion, "Battery:Not detected\n");
    lv_obj_set_style_text_align(ui_BatteryDescribtion, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BatteryDescribtion, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WireDescribtion = lv_label_create(ui_PowerPanel);
    lv_obj_set_width(ui_WireDescribtion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WireDescribtion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WireDescribtion, 0);
    lv_obj_set_y(ui_WireDescribtion, 30);
    lv_obj_set_align(ui_WireDescribtion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WireDescribtion, "Wire:Detected");
    lv_obj_set_style_text_align(ui_WireDescribtion, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WireDescribtion, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_ButtonCheck = ui_ButtonCheck;
    uic_CharacterName = ui_CharacterName;
    uic_CharacterName = ui_CharacterDescribe;
    uic_CharacterName = ui_PowerName;
    uic_CharacterName = ui_BatteryDescribtion;
    uic_CharacterName = ui_WireDescribtion;

}
