// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_HalfmindScreen_screen_init(void)
{
    ui_HalfmindScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HalfmindScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_halfmindIcon = lv_obj_create(ui_HalfmindScreen);
    lv_obj_remove_style_all(ui_halfmindIcon);
    lv_obj_set_width(ui_halfmindIcon, 100);
    lv_obj_set_height(ui_halfmindIcon, 80);
    lv_obj_set_x(ui_halfmindIcon, -41);
    lv_obj_set_y(ui_halfmindIcon, 4);
    lv_obj_set_align(ui_halfmindIcon, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_halfmindIcon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_halfmindIcon);
    lv_img_set_src(ui_Image1, &ui_img_1859145046);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 122
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 62
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, -21);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 128);

    ui_Image2 = lv_img_create(ui_halfmindIcon);
    lv_img_set_src(ui_Image2, &ui_img_1460800525);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 121
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_Image2, -14);
    lv_obj_set_y(ui_Image2, 13);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 128);

    ui_Image3 = lv_img_create(ui_halfmindIcon);
    lv_img_set_src(ui_Image3, &ui_img_1747580854);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Image3, 14);
    lv_obj_set_y(ui_Image3, -17);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 128);

    ui_Image4 = lv_img_create(ui_halfmindIcon);
    lv_img_set_src(ui_Image4, &ui_img_1747580854);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_Image4, -5);
    lv_obj_set_y(ui_Image4, -17);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image4, 128);

    ui_halfmindLabel = lv_label_create(ui_HalfmindScreen);
    lv_obj_set_width(ui_halfmindLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_halfmindLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_halfmindLabel, 42);
    lv_obj_set_y(ui_halfmindLabel, 0);
    lv_obj_set_align(ui_halfmindLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_halfmindLabel, "HALF\nMIND");
    lv_obj_set_style_text_color(ui_halfmindLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_halfmindLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_halfmindLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_HalfmindScreen = ui_HalfmindScreen;
    uic_halfmindIcon = ui_halfmindIcon;
    uic_halfmindLabel = ui_halfmindLabel;

}
