// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_OTAScreen_screen_init(void)
{
    ui_OTAScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_OTAScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NewFirmware = lv_label_create(ui_OTAScreen);
    lv_obj_set_width(ui_NewFirmware, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NewFirmware, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NewFirmware, 0);
    lv_obj_set_y(ui_NewFirmware, -37);
    lv_obj_set_align(ui_NewFirmware, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NewFirmware, "New Firmware");
    lv_obj_set_style_text_font(ui_NewFirmware, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NewFirmware2 = lv_label_create(ui_NewFirmware);
    lv_obj_set_width(ui_NewFirmware2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NewFirmware2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NewFirmware2, -1);
    lv_obj_set_y(ui_NewFirmware2, 0);
    lv_obj_set_align(ui_NewFirmware2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NewFirmware2, "New Firmware");
    lv_obj_set_style_text_font(ui_NewFirmware2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OperateGuide = lv_label_create(ui_OTAScreen);
    lv_obj_set_width(ui_OperateGuide, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OperateGuide, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OperateGuide, -2);
    lv_obj_set_y(ui_OperateGuide, 27);
    lv_obj_set_align(ui_OperateGuide, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OperateGuide, "Click: Apply\nRotate: Skip");
    lv_obj_set_style_text_font(ui_OperateGuide, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OperateGuide2 = lv_label_create(ui_OperateGuide);
    lv_obj_set_width(ui_OperateGuide2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OperateGuide2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OperateGuide2, -1);
    lv_obj_set_y(ui_OperateGuide2, 0);
    lv_obj_set_align(ui_OperateGuide2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OperateGuide2, "Click: Apply\nRotate: Skip");
    lv_obj_set_style_text_color(ui_OperateGuide2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OperateGuide2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OperateGuide2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OperateGuide3 = lv_label_create(ui_OperateGuide);
    lv_obj_set_width(ui_OperateGuide3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OperateGuide3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OperateGuide3, 1);
    lv_obj_set_y(ui_OperateGuide3, 0);
    lv_obj_set_align(ui_OperateGuide3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OperateGuide3, "Click: Apply\nRotate: Skip");
    lv_obj_set_style_text_color(ui_OperateGuide3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OperateGuide3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OperateGuide3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OperateGuide4 = lv_label_create(ui_OperateGuide);
    lv_obj_set_width(ui_OperateGuide4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OperateGuide4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OperateGuide4, 1);
    lv_obj_set_y(ui_OperateGuide4, 0);
    lv_obj_set_align(ui_OperateGuide4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OperateGuide4, "Click: Apply\nRotate: Skip");
    lv_obj_set_style_text_color(ui_OperateGuide4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OperateGuide4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OperateGuide4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VersionChange = lv_label_create(ui_OTAScreen);
    lv_obj_set_width(ui_VersionChange, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VersionChange, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VersionChange, 0);
    lv_obj_set_y(ui_VersionChange, -9);
    lv_obj_set_align(ui_VersionChange, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VersionChange, "V 1.0.2--------->V 1.2.2");

    uic_NewFirmware = ui_NewFirmware;
    uic_NewFirmware2 = ui_NewFirmware2;
    uic_OperateGuide = ui_OperateGuide;
    uic_OperateGuide2 = ui_OperateGuide2;
    uic_OperateGuide3 = ui_OperateGuide3;
    uic_OperateGuide4 = ui_OperateGuide4;
    uic_VersionChange = ui_VersionChange;

}
