// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_OperatingScreen_screen_init(void)
{
    ui_OperatingScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_OperatingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OperatingTime = lv_label_create(ui_OperatingScreen);
    lv_obj_set_width(ui_OperatingTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OperatingTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OperatingTime, 1);
    lv_obj_set_y(ui_OperatingTime, 0);
    lv_obj_set_align(ui_OperatingTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OperatingTime, "5:00");
    lv_obj_set_style_text_color(ui_OperatingTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OperatingTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OperatingTime, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time2 = lv_label_create(ui_OperatingTime);
    lv_obj_set_width(ui_Time2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time2, -1);
    lv_obj_set_y(ui_Time2, 0);
    lv_obj_set_align(ui_Time2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time2, "5:00");
    lv_obj_set_style_text_color(ui_Time2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Time2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time2, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time3 = lv_label_create(ui_OperatingTime);
    lv_obj_set_width(ui_Time3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Time3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time3, "5:00");
    lv_obj_set_style_text_color(ui_Time3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Time3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time3, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_OperatingScreen = ui_OperatingScreen;
    uic_OperatingTime = ui_OperatingTime;

}
