// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SleepScreen_screen_init(void)
{
    ui_SleepScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SleepScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_SleepScreen);
    lv_obj_set_width(ui_Panel3, 250);
    lv_obj_set_height(ui_Panel3, 122);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SleepCLock = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_SleepCLock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SleepCLock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SleepCLock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SleepCLock, "55:00");
    lv_obj_set_style_text_font(ui_SleepCLock, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SleepCLock1 = lv_label_create(ui_SleepCLock);
    lv_obj_set_width(ui_SleepCLock1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SleepCLock1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SleepCLock1, 1);
    lv_obj_set_y(ui_SleepCLock1, -1);
    lv_obj_set_align(ui_SleepCLock1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SleepCLock1, "55:00");
    lv_obj_set_style_text_font(ui_SleepCLock1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_ActiveScreen = ui_SleepScreen;

}
