// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SlaveActiveScreen_screen_init(void)
{
    ui_SlaveActiveScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SlaveActiveScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SlaveName = lv_label_create(ui_SlaveActiveScreen);
    lv_obj_set_width(ui_SlaveName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SlaveName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SlaveName, 0);
    lv_obj_set_y(ui_SlaveName, -45);
    lv_obj_set_align(ui_SlaveName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SlaveName, "Slave");
    lv_obj_set_style_text_color(ui_SlaveName, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SlaveName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SlaveName, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SlaveInf = lv_label_create(ui_SlaveActiveScreen);
    lv_obj_set_width(ui_SlaveInf, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SlaveInf, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SlaveInf, 0);
    lv_obj_set_y(ui_SlaveInf, 10);
    lv_obj_set_align(ui_SlaveInf, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SlaveInf, "Username:\nHostMac:\n");
    lv_obj_set_style_text_color(ui_SlaveInf, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SlaveInf, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SlaveInf, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_SlaveActiveScreen = ui_SlaveActiveScreen;
    uic_SlaveInf = ui_SlaveInf;

}
