// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ShutdownScreen_screen_init(void)
{
    ui_ShutdownScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ShutdownScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ShutdownGuide = lv_label_create(ui_ShutdownScreen);
    lv_obj_set_width(ui_ShutdownGuide, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ShutdownGuide, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ShutdownGuide, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ShutdownGuide, "See you next time");
    lv_obj_set_style_text_font(ui_ShutdownGuide, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShutdownGuide2 = lv_label_create(ui_ShutdownGuide);
    lv_obj_set_width(ui_ShutdownGuide2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ShutdownGuide2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ShutdownGuide2, 1);
    lv_obj_set_y(ui_ShutdownGuide2, 0);
    lv_obj_set_align(ui_ShutdownGuide2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ShutdownGuide2, "See you next time");
    lv_obj_set_style_text_font(ui_ShutdownGuide2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShutdownGuide3 = lv_label_create(ui_ShutdownGuide);
    lv_obj_set_width(ui_ShutdownGuide3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ShutdownGuide3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ShutdownGuide3, -1);
    lv_obj_set_y(ui_ShutdownGuide3, 0);
    lv_obj_set_align(ui_ShutdownGuide3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ShutdownGuide3, "See you next time");
    lv_obj_set_style_text_font(ui_ShutdownGuide3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShutdownGuide4 = lv_label_create(ui_ShutdownGuide);
    lv_obj_set_width(ui_ShutdownGuide4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ShutdownGuide4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ShutdownGuide4, 0);
    lv_obj_set_y(ui_ShutdownGuide4, 1);
    lv_obj_set_align(ui_ShutdownGuide4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ShutdownGuide4, "See you next time");
    lv_obj_set_style_text_font(ui_ShutdownGuide4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShutdownGuide5 = lv_label_create(ui_ShutdownGuide);
    lv_obj_set_width(ui_ShutdownGuide5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ShutdownGuide5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ShutdownGuide5, 0);
    lv_obj_set_y(ui_ShutdownGuide5, -1);
    lv_obj_set_align(ui_ShutdownGuide5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ShutdownGuide5, "See you next time");
    lv_obj_set_style_text_font(ui_ShutdownGuide5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_ShutdownScreen = ui_ShutdownScreen;
    uic_ShutdownGuide = ui_ShutdownGuide;
    uic_ShutdownGuide = ui_ShutdownGuide2;
    uic_ShutdownGuide = ui_ShutdownGuide3;
    uic_ShutdownGuide = ui_ShutdownGuide4;
    uic_ShutdownGuide = ui_ShutdownGuide5;

}
