// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ShutdownScreen_screen_init(void)
{
    ui_ShutdownScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ShutdownScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel13 = lv_obj_create(ui_ShutdownScreen);
    lv_obj_set_width(ui_Panel13, 250);
    lv_obj_set_height(ui_Panel13, 122);
    lv_obj_clear_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShutdownGuide = lv_label_create(ui_Panel13);
    lv_obj_set_width(ui_ShutdownGuide, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ShutdownGuide, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ShutdownGuide, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ShutdownGuide, "See you next time");
    lv_obj_add_flag(ui_ShutdownGuide, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_ShutdownGuide, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ShutdownGuide2 = lv_label_create(ui_ShutdownGuide);
    lv_obj_set_width(ui_ShutdownGuide2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ShutdownGuide2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ShutdownGuide2, -1);
    lv_obj_set_y(ui_ShutdownGuide2, 0);
    lv_obj_set_align(ui_ShutdownGuide2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ShutdownGuide2, "See you next time");
    lv_obj_set_style_text_font(ui_ShutdownGuide2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Battery = lv_img_create(ui_ShutdownScreen);
    lv_img_set_src(ui_Battery, &ui_img_battery_png);
    lv_obj_set_width(ui_Battery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Battery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Battery, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Battery, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Battery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_ShutdownScreen = ui_ShutdownScreen;
    uic_ShutdownGuide = ui_ShutdownGuide;
    uic_ShutdownGuide = ui_ShutdownGuide2;

}
