// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SlaveActiveScreen_screen_init(void)
{
    ui_SlaveActiveScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SlaveActiveScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel6 = lv_obj_create(ui_SlaveActiveScreen);
    lv_obj_set_width(ui_Panel6, 250);
    lv_obj_set_height(ui_Panel6, 122);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Panel6, &ui_img_hostactive_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Username = lv_label_create(ui_SlaveActiveScreen);
    lv_obj_set_width(ui_Username, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Username, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Username, 0);
    lv_obj_set_y(ui_Username, -12);
    lv_obj_set_align(ui_Username, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Username, "FUCK");
    lv_obj_set_style_text_font(ui_Username, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Username);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 1);
    lv_obj_set_y(ui_Label6, 0);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "FUCK");

    uic_SlaveActiveScreen = ui_SlaveActiveScreen;

}
