// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SleepClockScreen_screen_init(void)
{
    ui_SleepClockScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SleepClockScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TaskFocus4 = lv_obj_create(ui_SleepClockScreen);
    lv_obj_remove_style_all(ui_TaskFocus4);
    lv_obj_set_width(ui_TaskFocus4, 250);
    lv_obj_set_height(ui_TaskFocus4, 123);
    lv_obj_set_align(ui_TaskFocus4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TaskFocus4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_TaskFocus4, &ui_img_timebar_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TodoNum = lv_label_create(ui_TaskFocus4);
    lv_obj_set_width(ui_TodoNum, 180);
    lv_obj_set_height(ui_TodoNum, 30);
    lv_obj_set_align(ui_TodoNum, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_TodoNum, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_TodoNum, "24 to-dos");
    lv_obj_set_style_text_color(ui_TodoNum, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TodoNum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TodoNum, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TodoNum, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Task2 = lv_label_create(ui_TodoNum);
    lv_obj_set_width(ui_Task2, 180);
    lv_obj_set_height(ui_Task2, 30);
    lv_obj_set_x(ui_Task2, -1);
    lv_obj_set_y(ui_Task2, 0);
    lv_obj_set_align(ui_Task2, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Task2, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_Task2, "24 to-dos");
    lv_obj_set_style_text_color(ui_Task2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Task2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Task2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Task2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date = lv_label_create(ui_TaskFocus4);
    lv_obj_set_width(ui_Date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Date, 0);
    lv_obj_set_y(ui_Date, -25);
    lv_obj_set_align(ui_Date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Date, "Jun 23rd");
    lv_obj_set_style_text_font(ui_Date, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Date);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -1);
    lv_obj_set_y(ui_Label14, 0);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Jun 23rd");
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Hour = lv_label_create(ui_TaskFocus4);
    lv_obj_set_width(ui_Hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Hour, 0);
    lv_obj_set_y(ui_Hour, 25);
    lv_obj_set_align(ui_Hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Hour, "6 PM");

    ui_Label13 = lv_label_create(ui_Hour);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -1);
    lv_obj_set_y(ui_Label13, 0);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "6 PM");

    ui_MinuteBar = lv_arc_create(ui_TaskFocus4);
    lv_obj_set_width(ui_MinuteBar, 300);
    lv_obj_set_height(ui_MinuteBar, 300);
    lv_obj_set_align(ui_MinuteBar, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_MinuteBar, 0, 360);
    lv_arc_set_value(ui_MinuteBar, 45);
    lv_arc_set_bg_angles(ui_MinuteBar, 0, 360);
    lv_arc_set_rotation(ui_MinuteBar, 270);
    lv_obj_set_style_bg_color(ui_MinuteBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MinuteBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MinuteBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MinuteBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MinuteBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_MinuteBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MinuteBar, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MinuteBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_MinuteBar, lv_color_hex(0x401515), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_MinuteBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MinuteBar, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MinuteBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MinuteBar, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_MinuteBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_MinuteBar, 150, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_MinuteBar, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_img_src(ui_MinuteBar, &ui_img_fullbar_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MinuteBar, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MinuteBar, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MinuteBar, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MinuteBar, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_MinuteBar, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_MinuteBar, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    uic_FocusScreen = ui_SleepClockScreen;
    uic_TodoNum = ui_TodoNum;
    uic_Task = ui_Task2;

}
