// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_UpdateScreen_screen_init(void)
{
    ui_UpdateScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_UpdateScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel8 = lv_obj_create(ui_UpdateScreen);
    lv_obj_set_width(ui_Panel8, 250);
    lv_obj_set_height(ui_Panel8, 122);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VersionnNmber = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_VersionnNmber, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VersionnNmber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VersionnNmber, 0);
    lv_obj_set_y(ui_VersionnNmber, -9);
    lv_obj_set_align(ui_VersionnNmber, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VersionnNmber, "V 1.0.2");
    lv_obj_set_style_text_color(ui_VersionnNmber, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_VersionnNmber, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_VersionnNmber, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Updating = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Updating, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Updating, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Updating, 0);
    lv_obj_set_y(ui_Updating, -37);
    lv_obj_set_align(ui_Updating, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Updating, "Updating...");
    lv_obj_set_style_text_font(ui_Updating, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Updating2 = lv_label_create(ui_Updating);
    lv_obj_set_width(ui_Updating2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Updating2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Updating2, -1);
    lv_obj_set_y(ui_Updating2, 0);
    lv_obj_set_align(ui_Updating2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Updating2, "Updating...");
    lv_obj_set_style_text_font(ui_Updating2, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar = lv_bar_create(ui_Panel8);
    lv_bar_set_value(ui_Bar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar, 150);
    lv_obj_set_height(ui_Bar, 10);
    lv_obj_set_x(ui_Bar, 0);
    lv_obj_set_y(ui_Bar, 20);
    lv_obj_set_align(ui_Bar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Bar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Bar, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    uic_VersionnNmber = ui_VersionnNmber;
    uic_Updating = ui_Updating;
    uic_Updating2 = ui_Updating2;

}
